apiVersion: v1
kind: ConfigMap
metadata:
  name: kratos-react-config
data:
  kratos.yml: |-
    dsn: memory

    serve:
      public:
        base_url: https://public-kratos-react.external.rvu.cloud/public
        cors:
          enabled: true
      admin:
        base_url: https://admin-kratos-react.external.rvu.cloud/

    selfservice:
      default_browser_return_url: https://public-kratos-react.external.rvu.cloud/app
      whitelisted_return_urls:
        - https://public-kratos-react.external.rvu.cloud/app

      methods:
        totp:
          enabled: true
          config:
            issuer: Money.co.uk
        password:
          enabled: true
        oidc:
          enabled: true
          config:
            providers:
              - id: crm
                provider: generic
                client_id: kratos-react
                client_secret: mysecret
                scope:
                  - openid
                  - email
                mapper_url: file:///oidc/oidc-data-mapper.jsonnet
                issuer_url: https://crm-react-hydra-staging.external.rvu.cloud/
              - id: passwordless
                provider: generic
                client_id: kratos-react
                client_secret: mysecret
                scope:
                  - openid
                  - email
                mapper_url: file:///oidc/oidc-data-mapper.jsonnet
                issuer_url: https://oidc-react-staging.external.rvu.cloud/

      flows:
        error:
          ui_url: https://public-kratos-react.external.rvu.cloud/app/error

        settings:
          ui_url: https://public-kratos-react.external.rvu.cloud/app/settings
          privileged_session_max_age: 15m

        recovery:
          enabled: true
          ui_url: https://public-kratos-react.external.rvu.cloud/app/recovery

        verification:
          enabled: true
          ui_url: https://public-kratos-react.external.rvu.cloud/app/verification
          after:
            default_browser_return_url: https://public-kratos-react.external.rvu.cloud/app/

        logout:
          after:
            default_browser_return_url: https://public-kratos-react.external.rvu.cloud/app/login

        login:
          ui_url: https://public-kratos-react.external.rvu.cloud/app/login
          lifespan: 10m
          after:
            default_browser_return_url: https://public-kratos-react.external.rvu.cloud/app/

        registration:
          lifespan: 10m
          ui_url: https://public-kratos-react.external.rvu.cloud/app/registration
          after:
            password:
              hooks:
                - hook: session
            oidc:
              hooks:
                - hook: session
            default_browser_return_url: https://public-kratos-react.external.rvu.cloud/app/

    log:
      level: debug
      format: text
      leak_sensitive_values: true

    secrets:
      cookie:
        - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
      cipher:
        - MRBW6ZDFEBBGC43FGMZA300056789121

    ciphers:
      algorithm: xchacha20-poly1305

    session:
      cookie:
        domain: external.rvu.cloud
        same_site: Lax

    hashers:
      argon2:
        parallelism: 1
        memory: 128MB
        iterations: 2
        salt_length: 16
        key_length: 16

    identity:
      default_schema_url: file:///schema/identity.schema.json

    courier:
      smtp:
        connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true